server:
  port: 8001
spring:
  application:
    name: placeorder
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.133.139
    port: 5672
    username: guest
    password: guest
    virtual-host: /